name: PyPI
permissions:
  contents: read
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-root

      - name: Activate dynamic versioning
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Poetry build
        run: poetry build

      - name: PyPi publish
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: "${{ secrets.PYPI_API_TOKEN }}"
